// Generated by scripts/sync-reference.mjs from the frozen reasoning-visual.html.
// Slider, CSS, shaders, motion and presentation dependencies are copied verbatim.
// Explicit host adapters position/animate the popup, isolate CSS and queue selections.
(() => {
  const browser = window;
  let referenceModule;
  function captureReference(window) {
// BEGIN REFERENCE COMPONENT WITH HOST SELECTION ADAPTER
window.__ModuleLoader__.load({
	id: "dsh-reasoning-slider",
	factory: (require) => {
		const React = require("react");
		const { createPortal } = require("react-dom");
		const { MenuSurface, StateDot, IconChevronDownOutlineRegular, IconChevronRightOutlineRegular,
			IconCheckOutlineRegular, IconRefreshOutlineRegular, IconDataOutlineRegular,
			useAnchoredPosition, useDismissOnOutsidePointer, rankByName } = require("@deepseek-ai/dsh-client-ui-primitives");
		const h = React.createElement;
		const NS = "dsh-reasoning-slider";
		const TEXT = {
			zh: { chooseModel: "选择模型", chooseEffort: "选择强度", effort: "推理强度", picker: "模型与推理强度",
				reset: "重置推理强度", search: "搜索模型", empty: "没有可用模型", noResults: "没有匹配的模型",
				noEffort: "此模型未提供推理档位", unavailable: "当前模型不可用，请重新选择", loading: "正在加载模型…",
				saving: "正在应用选择…", failed: "选择失败，请重试", retry: "重试", writerHeld: "此会话正在其他 DSH 实例中使用，请退出其他实例后重试。" },
			en: { chooseModel: "Select model", chooseEffort: "Select effort", effort: "Reasoning effort", picker: "Model and reasoning effort",
				reset: "Reset reasoning effort", search: "Search models", empty: "No models available", noResults: "No matching models",
				noEffort: "This model provides no reasoning levels", unavailable: "This model is unavailable. Select another model.", loading: "Loading models…",
				saving: "Applying selection…", failed: "Selection failed. Try again.", retry: "Retry", writerHeld: "This session is in use by another DSH instance. Quit that instance and try again." }
		};
		// Ported geometry and motion from the locally inspected Codex 26.930.21537
		// ModelPickerPowerSliderImpl (impl-5f62465d8678.js / impl-1c8b0a94e9ce.css).
		// The native range, host bindings, menu, and async submission are DSH adapters.
		const MOTION = { thumb: 28, inset: 1, clickMs: 300, dragMs: 150, wheelThreshold: 30, wheelResetMs: 160,
			enter: { stiffness: 420, damping: 38 }, leave: { stiffness: 220, damping: 26 } };
		const BURST = [[-3,-34],[15,-29],[30,-19],[34,-2],[26,20],[12,31],[-6,34],[-22,26],[-32,9],[-32,-10],[-21,-26],[7,-24],[24,-9],[20,10],[-9,21],[-25,-5]];
		const BURST_DELAYS = [0,8,0,12,0,10,0,14,0,8,0,6,0,10,0,12];
		// GLSL copied verbatim from the local Codex slider; React/WebGL lifecycle adapted below.
		const ULTRA_VERTEX = `
  attribute vec2 aPosition;
  varying vec2 vUv;

  void main() {
    vUv = aPosition * 0.5 + 0.5;
    gl_Position = vec4(aPosition, 0.0, 1.0);
  }
`;
		const ULTRA_FRAGMENT = `
  precision highp float;

  varying vec2 vUv;

  uniform float uTime;
  uniform vec2 uResolution;

  const vec3 COLOR_1 = vec3(0.592, 0.388, 0.945);
  const vec3 COLOR_2 = vec3(0.831, 0.710, 0.953);
  const vec3 COLOR_3 = vec3(0.286, 0.000, 0.404);
  const vec3 COLOR_4 = vec3(0.145, 0.055, 0.478);
  const vec3 COLOR_5 = vec3(0.592, 0.000, 0.996);
  const vec3 COLOR_6 = vec3(0.780, 0.459, 0.914);
  const vec3 COLOR_7 = vec3(0.725, 0.576, 1.000);
  const vec3 COLOR_8 = vec3(0.400, 0.212, 0.820);
  const vec3 COLOR_9 = vec3(0.882, 0.690, 1.000);
  const vec3 COLOR_10 = vec3(0.498, 0.345, 0.957);
  const vec3 COLOR_11 = vec3(0.659, 0.275, 0.910);
  const vec3 COLOR_12 = vec3(0.212, 0.063, 0.400);

  float grain(vec2 uv) {
    vec2 grainUv = uv * uResolution * 0.5;
    return fract(sin(dot(grainUv + uTime, vec2(12.9898, 78.233))) * 43758.5453) * 2.0 - 1.0;
  }

  float fieldWeight(vec2 point, vec2 center) {
    return exp(-dot(point - center, point - center) * 12.0);
  }

  vec3 fieldColor(vec2 rawUv) {
    const float speed = 1.25;
    vec2 uv = vec2(rawUv.x, 0.40 + rawUv.y * 0.18);
    vec2 spatialScale = vec2(1.55, 1.0);
    vec2 point = uv * spatialScale;
    vec2 center1 = vec2(0.18 + sin(uTime * speed * 0.42) * 0.18, 0.36 + cos(uTime * speed * 0.50) * 0.42) * spatialScale;
    vec2 center2 = vec2(0.34 + cos(uTime * speed * 0.62) * 0.24, 0.62 + sin(uTime * speed * 0.47) * 0.38) * spatialScale;
    vec2 center3 = vec2(0.52 + sin(uTime * speed * 0.38) * 0.28, 0.30 + cos(uTime * speed * 0.58) * 0.36) * spatialScale;
    vec2 center4 = vec2(0.70 + cos(uTime * speed * 0.54) * 0.24, 0.68 + sin(uTime * speed * 0.41) * 0.36) * spatialScale;
    vec2 center5 = vec2(0.88 + sin(uTime * speed * 0.74) * 0.16, 0.36 + cos(uTime * speed * 0.64) * 0.40) * spatialScale;
    vec2 center6 = vec2(0.12 + cos(uTime * speed * 0.48) * 0.20, 0.72 + sin(uTime * speed * 0.70) * 0.30) * spatialScale;
    vec2 center7 = vec2(0.30 + sin(uTime * speed * 0.58) * 0.22, 0.44 + cos(uTime * speed * 0.52) * 0.42) * spatialScale;
    vec2 center8 = vec2(0.46 + cos(uTime * speed * 0.68) * 0.26, 0.72 + sin(uTime * speed * 0.56) * 0.32) * spatialScale;
    vec2 center9 = vec2(0.60 + sin(uTime * speed * 0.44) * 0.28, 0.26 + cos(uTime * speed * 0.60) * 0.38) * spatialScale;
    vec2 center10 = vec2(0.76 + cos(uTime * speed * 0.50) * 0.22, 0.54 + sin(uTime * speed * 0.66) * 0.40) * spatialScale;
    vec2 center11 = vec2(0.92 + sin(uTime * speed * 0.70) * 0.15, 0.66 + cos(uTime * speed * 0.46) * 0.30) * spatialScale;
    vec2 center12 = vec2(0.06 + cos(uTime * speed * 0.40) * 0.14, 0.32 + sin(uTime * speed * 0.60) * 0.40) * spatialScale;
    float weight1 = fieldWeight(point, center1) * (0.7 + 0.3 * sin(uTime * 0.91));
    float weight2 = fieldWeight(point, center2) * (0.7 + 0.3 * cos(uTime * 1.07));
    float weight3 = fieldWeight(point, center3) * (0.7 + 0.3 * sin(uTime * 0.76));
    float weight4 = fieldWeight(point, center4) * (0.7 + 0.3 * cos(uTime * 1.18));
    float weight5 = fieldWeight(point, center5) * (0.7 + 0.3 * sin(uTime * 1.03));
    float weight6 = fieldWeight(point, center6) * (0.7 + 0.3 * cos(uTime * 0.83));
    float weight7 = fieldWeight(point, center7) * (0.7 + 0.3 * sin(uTime * 1.24));
    float weight8 = fieldWeight(point, center8) * (0.7 + 0.3 * cos(uTime * 0.96));
    float weight9 = fieldWeight(point, center9) * (0.7 + 0.3 * sin(uTime * 1.11));
    float weight10 = fieldWeight(point, center10) * (0.7 + 0.3 * cos(uTime * 0.72));
    float weight11 = fieldWeight(point, center11) * (0.7 + 0.3 * sin(uTime * 1.29));
    float weight12 = fieldWeight(point, center12) * (0.7 + 0.3 * cos(uTime * 0.88));
    float totalWeight = max(
      weight1 + weight2 + weight3 + weight4 + weight5 + weight6 +
        weight7 + weight8 + weight9 + weight10 + weight11 + weight12,
      0.0001
    );
    vec3 color = (
      COLOR_1 * weight1 + COLOR_2 * weight2 + COLOR_3 * weight3 +
      COLOR_4 * weight4 + COLOR_5 * weight5 + COLOR_6 * weight6 +
      COLOR_7 * weight7 + COLOR_8 * weight8 + COLOR_9 * weight9 +
      COLOR_10 * weight10 + COLOR_11 * weight11 + COLOR_12 * weight12
    ) / totalWeight;
    color = mix(COLOR_4, color, 0.96);

    return pow(clamp(color, vec3(0.0), vec3(1.0)), vec3(0.9));
  }

  void main() {
    vec3 color = fieldColor(vUv);
    color += grain(vUv) * 0.012;
    color.r += sin(uTime * 0.5) * 0.02;
    color.g += cos(uTime * 0.7) * 0.02;
    color.b += sin(uTime * 0.6) * 0.02;
    color = pow(color, vec3(0.92));

    gl_FragColor = vec4(color, 1.0);
  }
`;
		const CSS = `
.dsh-reasoning-root { min-width:0; position:relative; }
.dsh-reasoning-trigger { display:inline-flex; align-items:center; gap:4px; max-width:min(280px, 45cqw, 52vw); min-width:0; height:28px; border:0; border-radius:999px; padding:2px 8px; background:transparent; color:var(--dsw-alias-label-primary); font:inherit; font-size:12px; cursor:pointer; }
.dsh-reasoning-trigger:hover, .dsh-reasoning-trigger[aria-expanded=true] { background:var(--dsw-alias-interactive-bg-hover, #8881); }
.dsh-reasoning-trigger > svg { width:14px; height:14px; flex:none; color:var(--dsw-alias-label-tertiary); }
.dsh-reasoning-trigger-icon { display:var(--dsh-composer-model-icon-display, none); }
.dsh-reasoning-trigger-model { display:var(--dsh-composer-model-text-display, block); overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }
.dsh-reasoning-trigger-effort { display:var(--dsh-composer-model-text-display, block); flex:none; color:var(--dsw-alias-label-tertiary); }
.dsh-reasoning-trigger:focus-visible, .dsh-reasoning-panel button:focus-visible, .dsh-reasoning-search:focus-visible { outline:2px solid var(--dsw-alias-state-business-primary, #3c83ff); outline-offset:2px; }
.dsh-reasoning-trigger:disabled, .dsh-reasoning-panel button:disabled { cursor:default; opacity:.55; }
.dsh-reasoning-panel[role=dialog] { --rs-blue:var(--dsw-alias-state-business-primary, #3c83ff); --rs-purple:#9863f1; --rs-ease:cubic-bezier(.23,1,.32,1); position:fixed; z-index:1200; box-sizing:border-box; width:256px; max-width:calc(100vw - 24px); max-height:calc(100dvh - 32px); overflow:auto; border:.5px solid var(--dsw-alias-border-l2, #0002); border-radius:16px; padding:8px; color:var(--dsw-alias-label-primary, #242629); --dsw-elevation-stroke-color:transparent; box-shadow:var(--dsw-elevation-prominent, 0 8px 24px #0002); animation:dsh-reasoning-open .16s var(--rs-ease); }
.dsh-reasoning-panel *, .dsh-reasoning-panel *::before { box-sizing:border-box; }
.dsh-reasoning-panel button { font:inherit; cursor:pointer; }
.dsh-reasoning-header { position:relative; display:flex; align-items:center; justify-content:center; min-height:44px; padding:2px 32px; }
.dsh-reasoning-model-link { display:flex; flex-direction:column; align-items:center; gap:2px; min-width:0; max-width:100%; padding:2px 4px; background:transparent; color:inherit; border:0; border-radius:6px; }
.dsh-reasoning-model-link:hover, .dsh-reasoning-icon:hover { background:var(--dsw-alias-interactive-bg-hover, #8881); }
.dsh-reasoning-label { max-width:100%; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; font-size:14px; font-weight:500; line-height:20px; color:var(--rs-blue); }
.dsh-reasoning-label[data-maximum=true] { color:var(--rs-purple); }
.dsh-reasoning-model-name { display:flex; align-items:center; gap:2px; max-width:100%; color:var(--dsw-alias-label-tertiary, #888); font-size:12px; line-height:18px; }
.dsh-reasoning-model-name > span { overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }
.dsh-reasoning-model-name svg { width:12px; height:12px; flex:none; }
.dsh-reasoning-icon { display:flex; align-items:center; justify-content:center; flex:none; width:24px; height:24px; padding:3px; border:0; border-radius:6px; background:transparent; color:var(--dsw-alias-label-tertiary, #888); }
.dsh-reasoning-icon svg { width:18px; height:18px; }
.dsh-reasoning-reset { position:absolute; right:4px; top:4px; }
.dsh-reasoning-slider-wrap { height:32px; padding:2px 6px; margin:0 2px; }
.dsh-reasoning-slider { --rs-duration:.3s; position:relative; display:flex; align-items:center; width:100%; height:28px; touch-action:none; }
.dsh-reasoning-slider[data-dragging=true] { --rs-duration:.15s; cursor:grabbing; }
.dsh-reasoning-track { position:relative; width:100%; height:24px; overflow:hidden; border-radius:12px; background:color-mix(in srgb, var(--dsw-alias-label-primary, #000) 10%, transparent); box-shadow:inset 0 0 0 .5px var(--dsw-alias-border-l2, #0002); }
.dsh-reasoning-range { position:absolute; inset:0; overflow:hidden; background:var(--rs-blue); border-radius:12px 0 0 12px; transform:var(--rs-fill); }
.dsh-reasoning-effects { pointer-events:none; position:absolute; inset:0; opacity:0; transform:var(--rs-effects); transition:opacity .3s var(--rs-ease); }
.dsh-reasoning-effects[data-visible=true] { opacity:1; }
.dsh-reasoning-ultra-fill { pointer-events:none; position:absolute; inset:-1px; z-index:2; }
.dsh-reasoning-ultra-mask { --rs-mask-position:0%; position:absolute; inset:0; contain:paint; isolation:isolate; background:linear-gradient(90deg, color-mix(in srgb, var(--rs-blue) 60%, var(--rs-purple)), var(--rs-purple) 55%, color-mix(in srgb, var(--rs-purple) 72%, var(--rs-blue))); -webkit-mask-image:linear-gradient(90deg, transparent calc(var(--rs-mask-position) - 120px), #000 var(--rs-mask-position), #000 100%); mask-image:linear-gradient(90deg, transparent calc(var(--rs-mask-position) - 120px), #000 var(--rs-mask-position), #000 100%); mask-size:100% 100%; mask-repeat:no-repeat; }
.dsh-reasoning-ultra-fill[data-reveal=true] .dsh-reasoning-ultra-mask { animation:dsh-reasoning-reveal 2s both; }
.dsh-reasoning-ultra-canvas { display:block; width:100%; height:100%; mix-blend-mode:luminosity; }
.dsh-reasoning-particles { pointer-events:none; position:absolute; z-index:3; inset:0; opacity:0; transition:opacity .35s cubic-bezier(.42,0,.58,1); }
.dsh-reasoning-effects[data-visible=true] .dsh-reasoning-particles { opacity:1; transition-delay:.15s; }
.dsh-reasoning-particle-track { pointer-events:none; position:absolute; inset-inline:0; top:50%; height:24px; overflow:hidden; transform:translateY(-50%); }
.dsh-reasoning-particle { position:absolute; width:3px; height:3px; border-radius:999px; background:#ffffffb8; box-shadow:0 0 5px #ffffff57; transition-property:left,top; transition-timing-function:cubic-bezier(.45,0,.55,1); }
.dsh-reasoning-tick { position:absolute; top:50%; left:var(--rs-position); width:4px; height:4px; border-radius:50%; transform:translate(-50%,-50%); background:color-mix(in srgb, var(--dsw-alias-label-tertiary, #888) 50%, transparent); transition:background-color var(--rs-duration) var(--rs-ease), opacity .2s ease-in-out, filter .12s ease, transform .12s ease; }
.dsh-reasoning-tick[data-filled=true] { background:#ffffff4d; }
.dsh-reasoning-slider[data-maximum=true] .dsh-reasoning-tick { opacity:0; transform:translate(-50%,-50%) scale(.75); transition:background-color var(--rs-duration) var(--rs-ease), opacity .4s ease-in-out .1s, filter .12s ease, transform .4s ease; }
.dsh-reasoning-slider:not([data-maximum=true]) .dsh-reasoning-tick[data-hovered=true] { filter:brightness(.85); transform:translate(-50%,-50%) scale(2); }
.dsh-reasoning-thumb-rail { pointer-events:none; position:absolute; z-index:4; top:50%; left:var(--rs-position); width:28px; height:28px; transform:translate(-50%,-50%); }
.dsh-reasoning-thumb { position:absolute; z-index:3; inset:0; border-radius:50%; background:#fff; border:.5px solid var(--dsw-alias-border-l2, #0002); box-shadow:0 0 2px #0000001a; transform-origin:50%; }
.dsh-reasoning-input { appearance:none; -webkit-appearance:none; position:absolute; z-index:3; top:0; left:-1px; width:calc(100% + 2px); height:28px; margin:0; padding:0; border:0; outline:0; background:transparent; color:transparent; cursor:pointer; touch-action:none; }
.dsh-reasoning-input::-webkit-slider-runnable-track { height:28px; background:transparent; }
.dsh-reasoning-input::-moz-range-track { height:28px; background:transparent; }
.dsh-reasoning-input::-webkit-slider-thumb { appearance:none; width:28px; height:28px; border:0; border-radius:50%; background:transparent; }
.dsh-reasoning-input::-moz-range-thumb { width:28px; height:28px; border:0; border-radius:50%; background:transparent; }
.dsh-reasoning-slider:has(.dsh-reasoning-input:focus-visible) .dsh-reasoning-thumb { outline:2px solid var(--rs-blue); }
.dsh-reasoning-slider[data-unknown=true] .dsh-reasoning-thumb-rail, .dsh-reasoning-slider[data-unknown=true] .dsh-reasoning-range { visibility:hidden; }
.dsh-reasoning-input:disabled { cursor:default; }
.dsh-reasoning-slider[data-disabled=true] { opacity:.6; }
.dsh-reasoning-slider[data-dragging=true] .dsh-reasoning-input { cursor:grabbing; }
.dsh-reasoning-burst { pointer-events:none; position:absolute; z-index:2; top:50%; left:50%; width:76px; height:76px; transform:translate(-50%,-50%); }
.dsh-reasoning-burst > i { position:absolute; left:50%; top:50%; width:5px; height:5px; border-radius:50%; background:var(--rs-purple); animation:dsh-reasoning-burst .62s cubic-bezier(.25,1,.5,1) both; }
.dsh-reasoning-burst > i:nth-child(4n+3) { background:color-mix(in srgb, var(--rs-purple) 82%, var(--rs-blue)); }
.dsh-reasoning-burst > i:nth-child(4n+1):not(:first-child) { background:color-mix(in srgb, var(--rs-purple) 68%, var(--rs-blue)); }
.dsh-reasoning-search { width:100%; border:0; border-radius:6px; margin:2px 0 6px; padding:6px 8px; background:transparent; color:inherit; font:inherit; font-size:12px; }
.dsh-reasoning-search::placeholder { color:var(--dsw-alias-label-tertiary, #888); }
.dsh-reasoning-model-list { max-height:min(316px, 60dvh); overflow:auto; overscroll-behavior:contain; }
.dsh-reasoning-group { margin:0; padding:6px 8px 2px; font-size:11px; font-weight:400; color:var(--dsw-alias-label-tertiary, #888); }
.dsh-reasoning-option { display:flex; align-items:center; justify-content:space-between; gap:12px; width:100%; min-height:30px; border:0; border-radius:8px; padding:6px 8px; text-align:left; background:transparent; color:inherit; font-size:13px !important; font-weight:400; }
.dsh-reasoning-option > span { overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }
.dsh-reasoning-option > svg { width:16px; height:16px; flex:none; }
.dsh-reasoning-option:hover, .dsh-reasoning-option:focus-visible, .dsh-reasoning-option[data-highlighted=true] { background:var(--dsw-alias-interactive-bg-hover, #8881); outline:0; }
.dsh-reasoning-notice { margin:4px 8px; font-size:12px; line-height:18px; color:var(--dsw-alias-label-tertiary, #888); overflow-wrap:anywhere; }
.dsh-reasoning-error { color:var(--dsw-alias-state-error-primary, #c92738); }
.dsh-reasoning-retry { border:0; background:transparent; color:var(--rs-blue); padding:4px 8px; border-radius:6px; }
.dsh-reasoning-sr { position:absolute; width:1px; height:1px; overflow:hidden; clip-path:inset(50%); white-space:nowrap; }
@keyframes dsh-reasoning-open { from { opacity:0; transform:translateY(3px) scale(.98); } to { opacity:1; transform:none; } }
@property --rs-mask-position { syntax:"<percentage>"; inherits:false; initial-value:0%; }
@keyframes dsh-reasoning-reveal { from { --rs-mask-position:100%; } to { --rs-mask-position:0%; } }
@keyframes dsh-reasoning-burst { 0% { opacity:0; transform:translate(-50%,-50%) scale(.25); } 22% { opacity:1; transform:translate(-50%,-50%) scale(1.28); } to { opacity:0; transform:translate(calc(-50% + var(--rs-x)),calc(-50% + var(--rs-y))) scale(.55); } }
@media (prefers-reduced-motion:reduce) { .dsh-reasoning-panel, .dsh-reasoning-panel * { animation:none !important; transition:none !important; } .dsh-reasoning-burst { display:none; } }
@media (forced-colors:active) { .dsh-reasoning-track { border:1px solid CanvasText; } .dsh-reasoning-range { background:Highlight !important; } .dsh-reasoning-thumb { background:Canvas; border:2px solid Highlight; } .dsh-reasoning-tick { background:CanvasText; } .dsh-reasoning-burst, .dsh-reasoning-effects { display:none; } }
`;

		function position(percent) {
			const offset = MOTION.thumb / 2 - MOTION.inset;
			return `calc(${percent}% + ${offset - percent / 50 * offset}px)`;
		}
		function fillPosition(percent, steps, factor = 1) {
			if (steps <= 0) return `translateX(${-100 * factor}%)`;
			const span = 100 / steps;
			const taper = Math.min(percent / span, (100 - percent) / span, 1);
			const offset = MOTION.thumb / 2 - MOTION.inset;
			return `translateX(calc(${(percent - 100) * factor}% + ${(offset - percent / 50 * offset) * taper * factor}px))`;
		}
		function modelChoices(groups) {
			return groups.flatMap((group) => group.models.map((model) => ({ group, model, key: JSON.stringify([group.id, model.id]) })));
		}
		function modelSelection(choice, current) {
			if (current?.provider === choice.group.id && current.model === choice.model.id) return current;
			const effort = choice.model.reasoning?.defaultEffort;
			return { provider: choice.group.id, model: choice.model.id, ...(effort === undefined ? {} : { reasoningEffort: effort }) };
		}
		function effortSelection(current, efforts, index) {
			if (!current || !Number.isInteger(index) || !efforts[index]) return null;
			return { provider: current.provider, model: current.model, reasoningEffort: efforts[index].id };
		}
		function sameSelection(a, b) {
			return a?.provider === b?.provider && a?.model === b?.model && a?.reasoningEffort === b?.reasoningEffort;
		}
		function isMaximumEffort(efforts, index) {
			// The host orders this model's levels; IDs/names vary between providers.
			return index >= 0 && index === efforts.length - 1;
		}
		function useReducedMotion() {
			const [reduced, setReduced] = React.useState(() => window.matchMedia("(prefers-reduced-motion: reduce)").matches);
			React.useEffect(() => {
				const media = window.matchMedia("(prefers-reduced-motion: reduce)");
				const update = () => setReduced(media.matches);
				update(); media.addEventListener("change", update);
				return () => media.removeEventListener("change", update);
			}, []);
			return reduced;
		}
		function easeProgress(progress) {
			if (progress <= 0 || progress >= 1) return Math.max(0, Math.min(1, progress));
			// Invert the x coordinate of Codex's cubic-bezier(.23, 1, .32, 1).
			let low = 0, high = 1, time = progress;
			for (let i = 0; i < 18; i++) {
				const x = 3 * (1 - time) ** 2 * time * .23 + 3 * (1 - time) * time ** 2 * .32 + time ** 3;
				if (Math.abs(x - progress) < 1e-7) break;
				if (x < progress) low = time; else high = time;
				time = (low + high) / 2;
			}
			return 1 - (1 - time) ** 3;
		}
		function tweenValue(tween, now) {
			return tween.from + (tween.to - tween.from) * easeProgress((now - tween.start) / tween.duration);
		}
		function useSliderMotion(ref, percent, steps, dragging, reduced) {
			const motion = React.useRef({ value: percent, tween: null });
			React.useLayoutEffect(() => {
				const element = ref.current;
				if (!element) return;
				const state = motion.current;
				const write = (value) => {
					state.value = value;
					element.style.setProperty("--rs-position", position(value));
					element.style.setProperty("--rs-fill", fillPosition(value, steps));
					element.style.setProperty("--rs-effects", fillPosition(value, steps, -.9));
				};
				if (reduced || !window.requestAnimationFrame) { state.tween = null; write(percent); return; }
				const now = window.performance.now();
				const from = state.tween ? tweenValue(state.tween, now) : state.value;
				write(from);
				if (from === percent) { state.tween = null; return; }
				const tween = state.tween = { from, to: percent, start: now, duration: dragging ? MOTION.dragMs : MOTION.clickMs };
				let frame;
				const tick = (time) => {
					write(tweenValue(tween, time));
					if (time - tween.start < tween.duration) frame = window.requestAnimationFrame(tick);
					else { state.tween = null; frame = null; }
				};
				frame = window.requestAnimationFrame(tick);
				return () => { if (frame != null) window.cancelAnimationFrame(frame); };
			}, [ref, percent, steps, dragging, reduced]);
		}
		function springValue(spring, now) {
			const time = Math.max(0, now - spring.start) / 1000;
			const decay = spring.damping / 2, frequency = Math.sqrt(spring.stiffness - decay * decay);
			const a = spring.from - spring.to, b = (spring.velocity + decay * a) / frequency;
			const sine = Math.sin(frequency * time), cosine = Math.cos(frequency * time), envelope = Math.exp(-decay * time);
			return { value: spring.to + envelope * (a * cosine + b * sine),
				velocity: envelope * ((b * frequency - decay * a) * cosine - (a * frequency + decay * b) * sine) };
		}
		function useThumbSpring(ref, expanded, reduced) {
			const motion = React.useRef({ value: 1, velocity: 0, spring: null });
			React.useLayoutEffect(() => {
				const element = ref.current;
				if (!element) return;
				const state = motion.current, to = !reduced && expanded ? 32 / 28 : 1;
				const write = ({ value, velocity }) => { state.value = value; state.velocity = velocity; element.style.transform = `scale(${value})`; };
				if (reduced || !window.requestAnimationFrame) { state.spring = null; write({ value: to, velocity: 0 }); return; }
				const now = window.performance.now();
				if (state.spring) write(springValue(state.spring, now));
				if (state.value === to && state.velocity === 0) return;
				const spring = state.spring = { from: state.value, velocity: state.velocity, to, start: now, ...(expanded ? MOTION.enter : MOTION.leave) };
				let frame;
				const tick = (time) => {
					const next = springValue(spring, time);
					if (Math.abs(next.value - to) < .001 && Math.abs(next.velocity) < .01) {
						write({ value: to, velocity: 0 }); state.spring = null; frame = null;
					} else { write(next); frame = window.requestAnimationFrame(tick); }
				};
				frame = window.requestAnimationFrame(tick);
				return () => { if (frame != null) window.cancelAnimationFrame(frame); };
			}, [ref, expanded, reduced]);
		}

		function startUltraCanvas(canvas, reduced) {
			if (!window.WebGLRenderingContext || !window.ResizeObserver) return;
			const gl = canvas.getContext("webgl", { alpha: true, antialias: false, depth: false, powerPreference: "high-performance", stencil: false });
			if (!gl) return;
			const compile = (type, source) => {
				const shader = gl.createShader(type);
				if (!shader) return null;
				gl.shaderSource(shader, source); gl.compileShader(shader);
				if (gl.getShaderParameter(shader, gl.COMPILE_STATUS)) return shader;
				gl.deleteShader(shader); return null;
			};
			const vertex = compile(gl.VERTEX_SHADER, ULTRA_VERTEX), fragment = compile(gl.FRAGMENT_SHADER, ULTRA_FRAGMENT);
			if (!vertex || !fragment) { if (vertex) gl.deleteShader(vertex); if (fragment) gl.deleteShader(fragment); return; }
			const program = gl.createProgram();
			if (program) { gl.attachShader(program, vertex); gl.attachShader(program, fragment); gl.linkProgram(program); }
			gl.deleteShader(vertex); gl.deleteShader(fragment);
			if (!program) return;
			if (!gl.getProgramParameter(program, gl.LINK_STATUS)) { gl.deleteProgram(program); return; }
			const buffer = gl.createBuffer();
			if (!buffer) { gl.deleteProgram(program); return; }
			const attribute = gl.getAttribLocation(program, "aPosition"), resolution = gl.getUniformLocation(program, "uResolution"), time = gl.getUniformLocation(program, "uTime");
			const start = window.performance.now();
			let frame = null;
			gl.useProgram(program); gl.bindBuffer(gl.ARRAY_BUFFER, buffer);
			gl.bufferData(gl.ARRAY_BUFFER, new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]), gl.STATIC_DRAW);
			gl.enableVertexAttribArray(attribute); gl.vertexAttribPointer(attribute, 2, gl.FLOAT, false, 0, 0);
			const draw = (seconds) => { gl.uniform1f(time, seconds); gl.drawArrays(gl.TRIANGLES, 0, 6); };
			const resize = () => {
				const ratio = Math.min(window.devicePixelRatio || 1, 2), rect = canvas.getBoundingClientRect();
				const width = Math.max(Math.round(rect.width), 1), height = Math.max(Math.round(rect.height), 1);
				canvas.width = Math.round(width * ratio); canvas.height = Math.round(height * ratio);
				gl.viewport(0, 0, canvas.width, canvas.height); gl.uniform2f(resolution, width, height);
				draw(reduced ? 0 : (window.performance.now() - start) / 1000);
			};
			const tick = (now) => { draw((now - start) / 1000); frame = window.requestAnimationFrame(tick); };
			const observer = new window.ResizeObserver(resize);
			resize(); observer.observe(canvas);
			if (!reduced) frame = window.requestAnimationFrame(tick);
			return () => { if (frame != null) window.cancelAnimationFrame(frame); observer.disconnect(); gl.deleteBuffer(buffer); gl.deleteProgram(program); };
		}
		function particleSeed(index, seed) {
			const value = Math.sin((index + 1) * 12.9898 + seed * 78.233) * 43758.5453;
			return value - Math.floor(value);
		}
		function particleTarget(random) {
			const x = random(), y = random();
			return { duration: 1.6 * (.8 + random() * 1.2), x: Math.round((x - .5) * 8), y: Math.round(12 + (y - .5) * 14) };
		}
		function TrackParticle({ index, active }) {
			const [target, setTarget] = React.useState(() => { let seed = 1; return particleTarget(() => particleSeed(index, seed++)); });
			React.useEffect(() => {
				if (!active || !window.requestAnimationFrame) return;
				let timer;
				const next = () => { const point = particleTarget(Math.random); setTarget(point); timer = window.setTimeout(next, point.duration * 1000); };
				const frame = window.requestAnimationFrame(next);
				return () => { window.cancelAnimationFrame(frame); window.clearTimeout(timer); };
			}, [active]);
			return h("i", { className: "dsh-reasoning-particle", style: { left: `calc(${Math.round(4 + particleSeed(index, 14) * 92)}% + ${target.x}px)`,
				top: target.y + "px", opacity: .4 + particleSeed(index, 11) * .6, transform: `translate(-50%,-50%) scale(${.5 + particleSeed(index, 12) * .45})`, transitionDuration: target.duration + "s" } });
		}
		function UltraEffects({ active, reveal, reduced }) {
			const canvas = React.useRef(null), [visible, setVisible] = React.useState(reduced);
			React.useEffect(() => startUltraCanvas(canvas.current, reduced), [reduced]);
			React.useEffect(() => {
				if (!active || reduced || !window.requestAnimationFrame) { setVisible(active); return; }
				const frame = window.requestAnimationFrame(() => setVisible(true));
				return () => window.cancelAnimationFrame(frame);
			}, [active, reduced]);
			return h("span", { className: "dsh-reasoning-effects", "data-visible": visible },
				h("span", { className: "dsh-reasoning-ultra-fill", "data-reveal": active && reveal && !reduced },
					h("span", { className: "dsh-reasoning-ultra-mask" }, h("canvas", { ref: canvas, className: "dsh-reasoning-ultra-canvas" }))),
				!reduced && h("span", { className: "dsh-reasoning-particles" }, h("span", { className: "dsh-reasoning-particle-track" },
					Array.from({ length: 14 }, (_, index) => h(TrackParticle, { key: index, index, active })))));
		}
		function useMaximumPresence(active, reduced) {
			const [present, setPresent] = React.useState(active);
			React.useEffect(() => {
				if (active || reduced) { setPresent(active); return; }
				if (!present) return;
				const timer = window.setTimeout(() => setPresent(false), MOTION.clickMs);
				return () => window.clearTimeout(timer);
			}, [active, reduced, present]);
			return active || present;
		}

		function ReasoningSlider({ efforts, value, disabled, reduced, label, onPreview, onCommit }) {
			const [draft, setDraft] = React.useState(null);
			const [dragging, setDragging] = React.useState(false);
			const [pressed, setPressed] = React.useState(false);
			const [hovered, setHovered] = React.useState(false);
			const [hoveredTick, setHoveredTick] = React.useState(-1);
			const [burst, setBurst] = React.useState(0);
			const slider = React.useRef(null), input = React.useRef(null), thumb = React.useRef(null), pointer = React.useRef(null);
			const latest = React.useRef(null), wheel = React.useRef({ delta: 0, time: 0 });
			const savedIndex = efforts.findIndex((effort) => effort.id === value);
			const index = draft ?? savedIndex;
			const blocked = disabled || efforts.length === 0 || efforts.length === 1 && savedIndex === 0;
			const steps = Math.max(efforts.length - 1, 0), percent = steps ? Math.max(index, 0) / steps * 100 : 0;
			const maximum = isMaximumEffort(efforts, index);
			const showMaximum = useMaximumPresence(maximum, reduced);
			const preview = (next) => {
				if (blocked || !efforts[next]) return;
				if (isMaximumEffort(efforts, next) && !maximum) setBurst((key) => key + 1);
				setDraft(next); onPreview(next);
			};
			const cancel = () => { pointer.current = null; setPressed(false); setDragging(false); setHovered(false); setHoveredTick(-1); setDraft(null); onPreview(null); };
			const commit = (next) => {
				cancel();
				if (!blocked && efforts[next] && (next !== savedIndex || savedIndex < 0)) {
					if (isMaximumEffort(efforts, next) && !maximum) setBurst((key) => key + 1);
					onCommit(next);
				}
			};
			const hover = (event) => {
				if (blocked) return;
				if (pointer.current !== null) { if (event.pointerId === pointer.current) setDragging(true); return; }
				const rect = thumb.current?.getBoundingClientRect();
				const overThumb = index >= 0 && Boolean(rect && event.clientX >= rect.left - 3 && event.clientX <= rect.right + 3 && event.clientY >= rect.top - 3 && event.clientY <= rect.bottom + 3);
				setHovered(overThumb);
				const track = slider.current?.getBoundingClientRect();
				const withinTrack = track && event.clientY >= track.top + 6 && event.clientY <= track.bottom - 6;
				const x = track ? event.clientX - track.left : 0, offset = MOTION.thumb / 2 - MOTION.inset;
				setHoveredTick(!overThumb && withinTrack ? efforts.findIndex((_, n) => Math.abs(x - (offset + (steps ? n / steps : 0) * (track.width - offset * 2))) <= 8) : -1);
			};
			latest.current = { blocked, index, commit };
			useSliderMotion(slider, percent, steps, dragging, reduced);
			useThumbSpring(thumb, !blocked && (hovered || pressed), reduced);
			React.useEffect(() => {
				const element = input.current;
				const onWheel = (event) => {
					if (latest.current.blocked || event.ctrlKey || pointer.current !== null) return;
					let delta = Math.abs(event.deltaX) > Math.abs(event.deltaY) ? event.deltaX : -event.deltaY;
					if (event.webkitDirectionInvertedFromDevice === true) delta *= -1;
					if (event.deltaMode !== 0) delta = Math.sign(delta) * MOTION.wheelThreshold;
					if (!delta) return;
					event.preventDefault(); event.stopPropagation();
					const acc = wheel.current;
					if (event.timeStamp - acc.time > MOTION.wheelResetMs || Math.sign(delta) !== Math.sign(acc.delta)) acc.delta = 0;
					acc.time = event.timeStamp; acc.delta += delta;
					if (Math.abs(acc.delta) < MOTION.wheelThreshold) return;
					const direction = Math.sign(acc.delta); acc.delta -= direction * MOTION.wheelThreshold;
					const next = latest.current.index < 0 ? 0 : Math.max(0, Math.min(steps, latest.current.index + direction));
					latest.current.commit(next);
				};
				element.addEventListener("wheel", onWheel, { passive: false });
				return () => element.removeEventListener("wheel", onWheel);
			}, [steps]);
			return h("div", { className: "dsh-reasoning-slider-wrap" }, h("div", {
				ref: slider, className: "dsh-reasoning-slider", "data-maximum": maximum, "data-unknown": index < 0, "data-disabled": blocked,
				"data-dragging": dragging, "data-reduced-motion": reduced
			}, h("div", { className: "dsh-reasoning-track", "aria-hidden": true },
				h("div", { className: "dsh-reasoning-range" }, showMaximum && h(UltraEffects, { active: maximum, reveal: burst > 0, reduced })), efforts.map((effort, n) => h("i", {
					key: effort.id, className: "dsh-reasoning-tick", "data-filled": n <= index, "data-hovered": !blocked && hoveredTick === n,
					style: { "--rs-position": position(steps ? n / steps * 100 : 0) }
				}))), h("div", { className: "dsh-reasoning-thumb-rail", "aria-hidden": true },
				maximum && burst > 0 && !reduced && h("span", { key: burst, className: "dsh-reasoning-burst" }, BURST.map(([x, y], n) =>
					h("i", { key: n, style: { "--rs-x": x + "px", "--rs-y": y + "px", animationDelay: BURST_DELAYS[n] + "ms" } }))),
				h("span", { ref: thumb, className: "dsh-reasoning-thumb" })),
				h("input", { ref: input, className: "dsh-reasoning-input", type: "range", min: 0, max: Math.max(steps, 1), step: 1,
					value: Math.max(index, 0), disabled: blocked, "aria-label": label, "aria-valuetext": efforts[index]?.name ?? label,
					onPointerEnter: hover, onPointerMove: hover, onPointerLeave: () => { setHovered(false); setHoveredTick(-1); },
					onPointerDown: (event) => {
						if (blocked || event.button !== 0 || event.isPrimary === false) return;
						pointer.current = event.pointerId; setPressed(true); setDragging(false); setHoveredTick(-1); event.currentTarget.setPointerCapture(event.pointerId);
					},
					onChange: (event) => { const next = Math.min(steps, event.currentTarget.valueAsNumber); preview(next); if (pointer.current === null) commit(next); },
					onPointerUp: (event) => { if (pointer.current === event.pointerId) commit(Math.min(steps, event.currentTarget.valueAsNumber)); },
					onPointerCancel: cancel, onLostPointerCapture: () => { if (pointer.current !== null) cancel(); }, onBlur: cancel,
					onKeyDown: (event) => {
						if (event.key === "Escape") cancel();
						if (savedIndex < 0 && ["ArrowLeft", "ArrowRight", "ArrowDown", "ArrowUp", "Home", "End"].includes(event.key)) {
							event.preventDefault(); commit(event.key === "End" ? steps : 0);
						}
					}
				})));
		}

		function ModelPicker({ locked, available, directory, load, select, t }) {
			const state = React.useSyncExternalStore(React.useCallback((fn) => directory.subscribe(fn), [directory]), () => directory.getSnapshot());
			const translate = t || ((key) => TEXT[/^zh/i.test(document.documentElement.lang) ? "zh" : "en"][key]);
			const [open, setOpen] = React.useState(false), [pane, setPane] = React.useState("effort"), [query, setQuery] = React.useState("");
			const [preview, setPreview] = React.useState(null), [error, setError] = React.useState(null), [saving, setSaving] = React.useState(false);
			const [highlight, setHighlight] = React.useState(0);
			const [optimistic, setOptimistic] = React.useState(null);
			const ignoredPending = React.useRef(null), access = React.useRef(null);
			access.current = { directory, allowed: available && !locked };
			const sameModel = (a, b) => Boolean(a && b && a.provider === b.provider && a.model === b.model);
			const root = React.useRef(null), trigger = React.useRef(null), panel = React.useRef(null), search = React.useRef(null), content = React.useRef(null);
			const mounted = React.useRef(false), inFlight = React.useRef(false), openRef = React.useRef(open);
			openRef.current = open;
			const reduced = useReducedMotion(), id = React.useId();
			const choices = React.useMemo(() => modelChoices(state.groups), [state.groups]);
			const pending = state.pending === ignoredPending.current ? null : state.pending;
			const current = optimistic ?? pending ?? state.current;
			const choice = choices.find((item) => item.group.id === current?.provider && item.model.id === current.model);
			const efforts = choice?.model.reasoning?.efforts ?? [];
			const effort = current?.reasoningEffort ?? choice?.model.reasoning?.defaultEffort;
			const effortLabel = (preview === null ? undefined : efforts[preview]?.name) ?? efforts.find((item) => item.id === effort)?.name ?? effort ?? (choice ? undefined : state.retainedEffort);
			const modelLabel = choice?.model.name ?? (current ? `${current.provider}/${current.model}` : translate("chooseModel"));
			const busy = saving || pending != null;
			const editingEffort = inFlight.current && !inFlight.current.modelChange && sameModel(current, state.current);
			const blocked = locked || busy && !editingEffort;
			const showSearch = choices.length > 4;
			const filtered = React.useMemo(() => state.groups.map((group) => ({ ...group,
				models: rankByName(group.models, showSearch ? query.trim() : "") })).filter((group) => group.models.length), [state.groups, query, showSearch]);
			const visible = modelChoices(filtered), activeIndex = Math.min(highlight, visible.length - 1);
			const placement = useAnchoredPosition({ open, anchorRef: trigger, panelRef: panel, side: "top", align: "center", gap: 8, margin: 12, contentRef: content, pane, reduced });
			useDismissOnOutsidePointer(root, open, setOpen, panel);
			React.useEffect(() => { mounted.current = true; return () => {
				mounted.current = false;
				if (inFlight.current) inFlight.current.queued = null;
			}; }, []);
			React.useEffect(() => {
				if ((locked || !available) && inFlight.current) inFlight.current.queued = null;
			}, [locked, available]);
			React.useEffect(() => {
				inFlight.current = false; ignoredPending.current = null;
				setSaving(false); setOptimistic(null);
				return () => { inFlight.current = false; };
			}, [directory]);
			React.useEffect(() => { if (available) load(); }, [available, load]);
			React.useEffect(() => { if (locked || !available) setOpen(false); }, [locked, available]);
			React.useEffect(() => { setPreview(null); }, [open, current?.provider, current?.model, effort]);
			React.useEffect(() => {
				if (!open) return;
				if (pane === "model") (showSearch ? search.current : panel.current?.querySelector('[aria-checked="true"]:not(:disabled)') ?? panel.current?.querySelector('[role="menuitemradio"]:not(:disabled)') ?? panel.current)?.focus({ preventScroll: true });
				else (panel.current?.querySelector('input[type="range"]:not(:disabled)') ?? panel.current?.querySelector("button"))?.focus({ preventScroll: true });
			}, [open, pane, showSearch]);
			React.useEffect(() => {
				if (open && pane === "model") panel.current?.querySelector('[data-highlighted="true"]')?.scrollIntoView({ block: "nearest" });
			}, [open, pane, activeIndex]);
			const close = (restore = false) => { setOpen(false); if (restore) trigger.current?.focus({ preventScroll: true }); };
			const openModels = () => { setQuery(""); setHighlight(Math.max(0, choices.findIndex((item) => item === choice))); setPane("model"); };
			const submit = async (selection, modelChange = false) => {
				if (!selection || locked || !available) return;
				const active = inFlight.current;
				if (active) {
					if (active.directory !== directory || modelChange || active.modelChange || !sameModel(selection, active.selection)) return;
					// Keep only the latest unsent effort. The current RPC is never raced.
					active.queued = selection;
					setOptimistic(selection); setError(null); setPreview(null);
					return;
				}
				if (pending != null) return;
				if (sameSelection(selection, state.current)) { if (modelChange) setPane("effort"); return; }
				const request = { selection, modelChange, queued: null, directory };
				inFlight.current = request; ignoredPending.current = null;
				setOptimistic(selection); setSaving(true); setError(null); setPreview(null);
				try {
					for (;;) {
						let result;
						try { result = await select(request.selection); }
						catch (reason) {
							// Some transports throw instead of returning a Remote Result. Do
							// not leave the input locked on that request's stale pending value.
							if (inFlight.current === request) ignoredPending.current = directory.getSnapshot().pending;
							result = { ok: false, error: { message: reason instanceof Error ? reason.message : translate("failed") } };
						}
						if (!mounted.current || inFlight.current !== request || access.current.directory !== directory) return;
						const next = request.queued;
						request.queued = null;
						if (next && access.current.allowed && sameModel(next, directory.getSnapshot().current) && !sameSelection(next, request.selection)) {
							request.selection = next;
							continue;
						}
						if (!result?.ok) setError(result?.error?.code === "session/writer-held" ? translate("writerHeld") : result?.error?.message ?? translate("failed"));
						else if (modelChange && openRef.current) { setQuery(""); setPane("effort"); }
						break;
					}
				} finally {
					if (inFlight.current === request && mounted.current) {
						inFlight.current = false;
						setSaving(false); setOptimistic(null);
						// An effort acknowledgement must not steal focus from a new drag.
						if (modelChange && openRef.current) queueMicrotask(() => {
							if (!mounted.current || !openRef.current) return;
							(panel.current?.querySelector('input[type="range"]:not(:disabled)') ?? search.current ?? panel.current?.querySelector("button:not(:disabled)"))?.focus({ preventScroll: true });
						});
					}
				}
			};
			const choose = (item) => { if (item && !locked && !busy) void submit(modelSelection(item, state.current), true); };
			const onKeyDown = (event) => {
				if (event.nativeEvent?.isComposing) return;
				if (event.key === "Escape") {
					event.preventDefault(); event.stopPropagation();
					if (pane === "model" && choice) setPane("effort"); else close(true);
					return;
				}
				if (pane === "model" && ["ArrowDown", "ArrowUp", "Home", "End"].includes(event.key) && !(event.target === search.current && ["Home", "End"].includes(event.key))) {
					event.preventDefault();
					if (!visible.length) return;
					const focused = Number(event.target.dataset?.modelIndex);
					const index = Number.isInteger(focused) ? focused : activeIndex;
					const next = event.key === "Home" ? 0 : event.key === "End" ? visible.length - 1 : (index + (event.key === "ArrowDown" ? 1 : -1) + visible.length) % visible.length;
					setHighlight(next); if (!showSearch) panel.current?.querySelector(`[data-model-index="${next}"]`)?.focus();
					return;
				}
				if (pane === "model" && event.target === search.current && event.key === "Enter") { event.preventDefault(); choose(visible[activeIndex]); }
				if (event.key === "Tab") {
					const items = [...panel.current.querySelectorAll('button:not(:disabled),input:not(:disabled)')];
					const index = items.indexOf(document.activeElement), next = index + (event.shiftKey ? -1 : 1);
					event.preventDefault(); if (next < 0 || next >= items.length) close(true); else items[next].focus();
				}
			};
			if (!available) return null;
			const resetEffort = choice?.model.reasoning?.defaultEffort;
			const resetIndex = efforts.findIndex((item) => item.id === resetEffort);
			// Effort acknowledgements must not remount the range and interrupt its motion.
			const selectionKey = JSON.stringify([current?.provider, current?.model, efforts.map((item) => item.id)]);
			let modelIndex = 0;
			return h("div", { ref: root, className: "dsh-reasoning-root" },
				h("button", { ref: trigger, type: "button", className: "dsh-reasoning-trigger", disabled: locked,
					"aria-label": `${translate("picker")}: ${modelLabel}${effortLabel ? ` · ${effortLabel}` : ""}`,
					"aria-haspopup": "dialog", "aria-expanded": open, "aria-controls": open ? id : undefined, "aria-busy": busy,
					title: `${modelLabel}${effortLabel ? ` · ${effortLabel}` : ""}`,
					onClick: () => { if (open) close(true); else { setError(null); setPreview(null); setQuery(""); setPane(choice ? "effort" : "model"); setOpen(true); load(); } },
					onKeyDown: (event) => { if (event.key === "ArrowDown" || event.key === "ArrowUp") { event.preventDefault(); setPane(choice ? "effort" : "model"); setOpen(true); } }
				}, h(IconDataOutlineRegular, { className: "dsh-reasoning-trigger-icon" }),
				h("span", { className: "dsh-reasoning-trigger-model" }, modelLabel),
				effortLabel && h("span", { className: "dsh-reasoning-trigger-effort", "data-maximum": isMaximumEffort(efforts, preview ?? efforts.findIndex((item) => item.id === effort)) || undefined }, effortLabel),
				h(IconChevronDownOutlineRegular)),
				open && createPortal(h(MenuSurface, { ref: panel, id, role: "dialog", "aria-label": translate("picker"), "aria-busy": busy, tabIndex: pane === "model" && busy && !showSearch ? -1 : undefined,
					className: "dsh-reasoning-panel", style: placement ?? { visibility: "hidden", top: 0, left: 0 }, onKeyDown,
					onBlur: (event) => { if (event.relatedTarget && !panel.current?.contains(event.relatedTarget) && !root.current?.contains(event.relatedTarget)) close(); }
				}, h("div", { ref: content, className: "dsh-reasoning-content" }, pane === "effort" ? h(React.Fragment, null,
					h("div", { className: "dsh-reasoning-header" },
						h("button", { type: "button", className: "dsh-reasoning-model-link", onClick: openModels, disabled: locked, "aria-label": translate("chooseModel") },
							h("span", { className: "dsh-reasoning-label", "data-maximum": isMaximumEffort(efforts, preview ?? efforts.findIndex((item) => item.id === effort)) }, effortLabel ?? translate("chooseEffort")),
							h("span", { className: "dsh-reasoning-model-name" }, h("span", null, modelLabel), h(IconChevronRightOutlineRegular))),
						resetIndex >= 0 && h("button", { type: "button", className: "dsh-reasoning-icon dsh-reasoning-reset", disabled: blocked || effort === resetEffort,
							"aria-label": translate("reset"), title: translate("reset"), onClick: () => void submit(effortSelection(current, efforts, resetIndex)) }, h(IconRefreshOutlineRegular))),
					efforts.length ? h(ReasoningSlider, { key: selectionKey, efforts, value: effort, disabled: blocked || !choice, reduced,
						label: translate("effort"), onPreview: setPreview, onCommit: (index) => void submit(effortSelection(current, efforts, index)) }) :
						h("p", { className: "dsh-reasoning-notice" }, translate(choice ? "noEffort" : "unavailable"))) :
					h(React.Fragment, null,
						showSearch && h("input", { ref: search, className: "dsh-reasoning-search", type: "search", value: query, placeholder: translate("search"), "aria-label": translate("search"),
							"aria-controls": id + "-models", "aria-activedescendant": activeIndex >= 0 ? id + "-model-" + activeIndex : undefined,
							onChange: (event) => { setQuery(event.currentTarget.value); setHighlight(0); } }),
						h("div", { id: id + "-models", className: "dsh-reasoning-model-list", role: "menu", "aria-label": translate("chooseModel") },
							filtered.map((group) => h("div", { key: group.id, role: "group", "aria-label": group.name },
								state.groups.length > 1 && h("div", { className: "dsh-reasoning-group" }, group.name),
								group.models.map((model) => { const index = modelIndex++; const item = visible[index]; return h("button", {
									key: item.key, id: id + "-model-" + index, type: "button", role: "menuitemradio", className: "dsh-reasoning-option", disabled: locked || busy,
									"aria-checked": group.id === current?.provider && model.id === current.model, "data-model-index": index, "data-highlighted": showSearch && activeIndex === index,
									onClick: () => choose(item), onFocus: () => setHighlight(index)
								}, h("span", null, model.name), group.id === current?.provider && model.id === current.model && (busy ? h(StateDot, { state: "ongoing" }) : h(IconCheckOutlineRegular))); }))),
							visible.length === 0 && h("p", { className: "dsh-reasoning-notice", role: "status" }, translate(state.status === "loading" ? "loading" : query ? "noResults" : "empty")))),
					(state.failures ?? []).map((failure) => h("p", { key: failure.id, className: "dsh-reasoning-notice dsh-reasoning-error" }, `${failure.name}: ${failure.message}`)),
					(error || state.error) && h("p", { role: "alert", className: "dsh-reasoning-notice dsh-reasoning-error" }, error || state.error),
					(state.error || state.failures?.length > 0) && h("button", { type: "button", className: "dsh-reasoning-retry", disabled: busy, onClick: () => { setError(null); load(); } }, translate("retry")),
					h("span", { role: "status", "aria-live": "polite", className: "dsh-reasoning-sr" }, busy ? translate("saving") : effortLabel)
				)), document.body));
		}

		function apply(ctx) {
			const locale = ctx.get("locale");
			if (locale) ctx.effect(() => locale.register(NS, TEXT), NS + ": dictionaries");
			ctx.effect(() => { const style = document.createElement("style"); style.dataset.plugin = NS; style.textContent = CSS;
				document.head.append(style); return () => style.remove(); }, NS + ": styles");
			ctx.inject(["slots", "modelDirectories", "sessions"], (scope) => {
				scope.slots.inject("conversation.input.model", () => scope.slots.register({
					// Codex Subscription already uses -10; single-slot priorities must be unique.
					name: "conversation.input.model", priority: -20, ...(locale ? { locale: NS } : {}),
					inject: (sessionId) => {
						const directory = scope.modelDirectories.directoryFor(sessionId);
						const available = scope.sessions.subagentAddress(sessionId) === undefined;
						return { available, directory: directory.store,
							load: () => { if (available) directory.load().catch(() => {}); },
							select: (selection) => available ? directory.select(selection) : Promise.resolve(undefined) };
					}
				}, ModelPicker));
			});
		}
		return { apply, inject: ["slots"] };
	}
});

// END REFERENCE COMPONENT WITH HOST SELECTION ADAPTER
    // Factories close over this binding; restore the real Window before loading.
    window = browser;
  }
  captureReference({ __ModuleLoader__: { load(module) { referenceModule = module; } } });
  browser.__ModuleLoader__.load({
    id: referenceModule.id,
    factory(require) {
      const React = require("react"), h = React.createElement;
// BEGIN VERBATIM PRESENTATION DEPENDENCIES
  const icons={IconChevronDownOutlineRegular:'m4 6 4 4 4-4',IconChevronRightOutlineRegular:'m6 3 5 5-5 5',
    IconCheckOutlineRegular:'m2 8 4 4 8-9',IconRefreshOutlineRegular:'M3 5a6 6 0 1 1-1 5 M3 1v4h4',IconDataOutlineRegular:'M2 3h12M2 8h12M2 13h12'};
  const primitives={
    MenuSurface:React.forwardRef((props,ref)=>h('div',{...props,ref})),StateDot:()=>h('span',null,'…'),
    rankByName:(models,query)=>models.filter(model=>model.name.toLowerCase().includes(query.toLowerCase())),
    useAnchoredPosition({open,anchorRef,panelRef}){
      const [placement,setPlacement]=React.useState(null);
      React.useLayoutEffect(()=>{
        if(!open||!panelRef.current)return;
        const update=()=>{const rect=anchorRef.current.getBoundingClientRect();setPlacement({top:Math.max(100,rect.top-panelRef.current.offsetHeight-8),left:rect.right-panelRef.current.offsetWidth});};
        update();const observer=new ResizeObserver(update);observer.observe(panelRef.current);return()=>observer.disconnect();
      },[open]);return placement;
    },
    useDismissOnOutsidePointer(root,open,setOpen,panel){React.useEffect(()=>{
      if(!open)return;const close=event=>{if(!root.current?.contains(event.target)&&!panel.current?.contains(event.target))setOpen(false);};
      document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close);
    },[open]);}
  };
  for(const [name,path] of Object.entries(icons))primitives[name]=props=>h('svg',{viewBox:'0 0 16 16',fill:'none',stroke:'currentColor',strokeWidth:1.5,...props},h('path',{d:path}));
// END VERBATIM PRESENTATION DEPENDENCIES
      const hostPrimitives = { ...primitives, useAnchoredPosition: (function createCenteredPosition(React) {
  const duration = 520, steps = 65;
  // Underdamped spring, mass 1 / stiffness 420 / damping 32. Sampled keyframes
  // let the browser run it without React renders or layout reads each frame.
  const spring = (from, to, velocity, ms) => {
    const time = ms / 1000, decay = 16, frequency = Math.sqrt(420 - decay * decay);
    const a = from - to, b = (velocity + decay * a) / frequency;
    return to + Math.exp(-decay * time) * (a * Math.cos(frequency * time) + b * Math.sin(frequency * time));
  };
  const sample = motion => {
    const position = Math.max(0, Math.min(steps, (Number(motion.animation.currentTime) || 0) / duration * steps));
    const index = Math.min(steps - 1, Math.floor(position)), fraction = position - index;
    const first = motion.values[index], last = motion.values[index + 1];
    const result = { velocity: {} };
    for (const key of ["top", "height"]) {
      result[key] = first[key] + (last[key] - first[key]) * fraction;
      result.velocity[key] = position === steps ? 0 : (last[key] - first[key]) * steps / duration * 1000;
    }
    return result;
  };
  return function useCenteredPosition({ open, anchorRef, panelRef, contentRef, pane, reduced, gap = 8, margin = 12 }) {
    const [placement, setPlacement] = React.useState(null);
    const controller = React.useRef(null), options = React.useRef(null);
    options.current = { pane, reduced };
    React.useLayoutEffect(() => {
      if (!open) { setPlacement(null); return; }
      const anchor = anchorRef.current, panel = panelRef.current, content = contentRef.current;
      if (!anchor || !panel || !content) return;
      let target = null, lastPane = null, motion = null, entrance = null, anchorRect = null, contentLimit = null;
      const stop = (keepEntrance = false) => {
        if (motion) { motion.animation.onfinish = null; motion.animation.cancel(); }
        motion = null;
        if (!keepEntrance) { entrance?.cancel(); entrance = null; }
      };
      const update = () => {
        const { pane, reduced } = options.current;
        const rect = anchor.getBoundingClientRect();
        anchorRect = rect;
        const style = window.getComputedStyle(panel);
        const chrome = [style.paddingTop, style.paddingBottom, style.borderTopWidth, style.borderBottomWidth]
          .reduce((sum, value) => sum + (parseFloat(value) || 0), 0);
        const limit = style.maxHeight && style.maxHeight !== "none" ? `calc(${style.maxHeight} - ${chrome}px)` : "";
        if (contentLimit !== limit) { content.style.maxHeight = limit; contentLimit = limit; }
        const width = panel.offsetWidth;
        // Height animation never constrains this flex item. Its natural height
        // remains measurable even when a pane switch interrupts an animation.
        const inset = motion ? target.inset : panel.offsetHeight - content.offsetHeight;
        const height = content.offsetHeight + inset;
        const viewportWidth = document.documentElement.clientWidth || window.innerWidth;
        const viewportHeight = document.documentElement.clientHeight || window.innerHeight;
        const clamp = (value, end) => Math.max(margin, Math.min(value, end - margin));
        const left = clamp(rect.left + (rect.width - width) / 2, viewportWidth - width);
        const above = rect.top - gap - height, below = rect.bottom + gap;
        const useBelow = above < margin && below + height <= viewportHeight - margin;
        const top = clamp(useBelow ? below : above, viewportHeight - height);
        const changedPane = target && lastPane !== pane;
        const changedSize = target && (target.top !== top || target.left !== left || target.height !== height || target.width !== width);
        if (target && !changedPane && !changedSize && !reduced) return;
        const animate = target && !reduced && typeof panel.animate === "function" &&
          (changedPane || motion && changedSize);
        const from = motion ? sample(motion) : target && { ...target, velocity: { top: 0, height: 0 } };
        stop(animate && !changedPane);
        target = { top, left, width, height, inset }; lastPane = pane;
        setPlacement(previous => previous?.left === left && previous.top === top ? previous : { left, top });
        if (!animate) return;
        // Limit the small rebound at viewport edges, preserving the 8px gap
        // wherever there is room above/below the trigger.
        const room = useBelow ? viewportHeight - margin - below : rect.top - gap - margin;
        const maxHeight = Math.max(from.height, height, Math.min(viewportHeight - 32, room));
        const values = Array.from({ length: steps + 1 }, (_, index) => {
          if (index === steps) return { top, height };
          const time = index / steps * duration;
          const rawHeight = spring(from.height, height, from.velocity.height, time);
          const nextHeight = Math.max(inset, Math.min(rawHeight, maxHeight));
          const rawTop = spring(from.top, top, from.velocity.top, time);
          return { height: nextHeight, top: clamp(rawTop + (useBelow ? 0 : rawHeight - nextHeight), viewportHeight - nextHeight) };
        });
        const animation = panel.animate(values.map(value => ({ top: `${value.top}px`, height: `${value.height}px` })),
          { duration, easing: "linear", fill: "both" });
        motion = { animation, values };
        if (changedPane) {
          const distance = pane === "model" ? 12 : -6;
          entrance = content.animate(Array.from({ length: steps + 1 }, (_, index) => {
            const time = index / steps * duration;
            return { transform: `translateY(${index === steps ? 0 : spring(distance, 0, 0, time)}px)`,
              opacity: 1 - Math.pow(1 - Math.min(1, time / 140), 3) };
          }), { duration, easing: "linear", fill: "both" });
        }
        animation.onfinish = () => { if (motion?.animation === animation) stop(); };
      };
      // A viewport/anchor move must track immediately, not trail the input.
      const reposition = event => {
        // Menu focus/scrollIntoView and list scrolling do not move the anchor.
        if (event?.target instanceof Node && panel.contains(event.target)) return;
        stop(); update();
      };
      controller.current = update;
      update();
      const observer = typeof ResizeObserver === "undefined" ? null : new ResizeObserver((entries = []) => {
        if (entries.some(entry => entry.target === anchor)) {
          const rect = anchor.getBoundingClientRect();
          if (rect.top !== anchorRect.top || rect.bottom !== anchorRect.bottom) { reposition(); return; }
        }
        update();
      });
      observer?.observe(anchor);
      observer?.observe(content);
      window.addEventListener("resize", reposition);
      window.addEventListener("scroll", reposition, true);
      return () => {
        controller.current = null;
        stop();
        observer?.disconnect();
        window.removeEventListener("resize", reposition);
        window.removeEventListener("scroll", reposition, true);
      };
    }, [open, anchorRef, panelRef, contentRef, gap, margin]);
    React.useLayoutEffect(() => { controller.current?.(); }, [pane, reduced]);
    return placement;
  };
})(React) };
      const plugin = referenceModule.factory(name => name === "@deepseek-ai/dsh-client-ui-primitives" ? hostPrimitives : require(name));
      const pageCSS = ":where(.dsh-reasoning-root, .dsh-reasoning-panel) { color-scheme:light; --dsw-alias-label-primary:#242629; --dsw-alias-label-tertiary:#8a8d93; --dsw-alias-border-l2:#0002; --dsw-alias-interactive-bg-hover:#f0f1f2; --dsw-alias-state-business-primary:#3c83ff; --surface:#fff;  --rs-purple:#9863f1; }\n:where(.dsh-reasoning-root, .dsh-reasoning-panel) { font:14px system-ui; color:var(--dsw-alias-label-primary); }\n:where(.dsh-reasoning-root button, .dsh-reasoning-panel button) { font:inherit; cursor:pointer; }\n.dsh-reasoning-trigger { background:var(--dsw-alias-interactive-bg-hover); }\n.dsh-reasoning-panel { background:var(--surface); }\nbody.dark :where(.dsh-reasoning-root, .dsh-reasoning-panel) { --surface:#282a2e; --dsw-alias-label-primary:#eee; --dsw-alias-label-tertiary:#a3a5ad; --dsw-alias-border-l2:#fff3; --dsw-alias-interactive-bg-hover:#383a3f; }";
      const hostCSS = "\n.dsh-reasoning-trigger-effort[data-maximum=true] { color:var(--rs-purple); }\n:is(.dsh-reasoning-root, .dsh-reasoning-panel) { --dsw-corner-shape:round; }\n:is(.dsh-reasoning-root, .dsh-reasoning-panel),\n:is(.dsh-reasoning-root, .dsh-reasoning-panel) *,\n:is(.dsh-reasoning-root, .dsh-reasoning-panel)::before,\n:is(.dsh-reasoning-root, .dsh-reasoning-panel)::after,\n:is(.dsh-reasoning-root, .dsh-reasoning-panel) *::before,\n:is(.dsh-reasoning-root, .dsh-reasoning-panel) *::after { corner-shape:round; }\n.dsh-reasoning-input::-webkit-slider-thumb { corner-shape:round; }\n.dsh-reasoning-input::-moz-range-thumb { corner-shape:round; }\n/* Decorative bursts must not create a scrollport or change the rail width. */\n.dsh-reasoning-panel[role=dialog] { display:flex; flex-direction:column; overflow:clip; }\n/* The hook derives max-height from the shell's actual padding and borders. */\n.dsh-reasoning-content { display:flex; flex-direction:column; flex-shrink:0; min-height:0; }\n.dsh-reasoning-header, .dsh-reasoning-slider-wrap, .dsh-reasoning-search, .dsh-reasoning-retry { flex-shrink:0; }\n.dsh-reasoning-model-list { min-height:0; }\n.dsh-reasoning-content > .dsh-reasoning-notice { min-height:0; overflow:auto; overflow-wrap:anywhere; overscroll-behavior:contain; }\n";
      return {
        ...plugin,
        apply(ctx) {
          ctx.effect(() => {
            const style = document.createElement("style");
            style.dataset.plugin = "dsh-reasoning-slider-page";
            style.textContent = pageCSS;
            document.head.append(style);
            return () => style.remove();
          }, "dsh-reasoning-slider: reference page inheritance");
          const result = plugin.apply(ctx);
          ctx.effect(() => {
            const style = document.createElement("style");
            style.dataset.plugin = "dsh-reasoning-slider-host";
            style.textContent = hostCSS;
            document.head.append(style);
            return () => style.remove();
          }, "dsh-reasoning-slider: host CSS isolation");
          return result;
        }
      };
    }
  });
})();
